#!/bin/sh

# Script for installation of PRISM-games on a clean install of Cygwin
# already set up with required packages, e.g., via prism-install-windows.bat

set -e # Abort if one of the commands fails
set -x # Print commands as they are executed

# Download the latest development version from GitHub
git clone https://github.com/prismmodelchecker/prism-games.git

# Compile PRISM-games and run a few tests (unless --nobuild passed)
# (should ultimately display: "Testing result: PASS")
if [ "$*" = "${*/--nobuild}" ]; then
  (cd prism-games/prism && make && make test testz3)
fi
