#!/bin/sh

# Script for installation of PRISM-games on a clean install of Cygwin
# already set up with required packages, e.g., via prism-install-win

set -e # Abort if one of the commands fails
set -x # Print commands as they are executed

# Download the latest development version from GitHub
git clone https://github.com/prismmodelchecker/prism-games.git

# Compile PRISM-games and run a few tests
# (each should display: "Testing result: PASS")
(cd prism-games/prism && make && make test testz3)
