/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int CLOCK = 5;
  /** RegularExpression Id. */
  int CONST = 6;
  /** RegularExpression Id. */
  int CTMC = 7;
  /** RegularExpression Id. */
  int CTMDP = 8;
  /** RegularExpression Id. */
  int C = 9;
  /** RegularExpression Id. */
  int DOUBLE = 10;
  /** RegularExpression Id. */
  int DTMC = 11;
  /** RegularExpression Id. */
  int E = 12;
  /** RegularExpression Id. */
  int ENDINIT = 13;
  /** RegularExpression Id. */
  int ENDINVARIANT = 14;
  /** RegularExpression Id. */
  int ENDMODULE = 15;
  /** RegularExpression Id. */
  int ENDPLAYER = 16;
  /** RegularExpression Id. */
  int ENDREWARDS = 17;
  /** RegularExpression Id. */
  int ENDSYSTEM = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int FORMULA = 20;
  /** RegularExpression Id. */
  int FILTER = 21;
  /** RegularExpression Id. */
  int FUNC = 22;
  /** RegularExpression Id. */
  int F = 23;
  /** RegularExpression Id. */
  int Fc = 24;
  /** RegularExpression Id. */
  int F0 = 25;
  /** RegularExpression Id. */
  int GLOBAL = 26;
  /** RegularExpression Id. */
  int G = 27;
  /** RegularExpression Id. */
  int INIT = 28;
  /** RegularExpression Id. */
  int INVARIANT = 29;
  /** RegularExpression Id. */
  int I = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int LABEL = 32;
  /** RegularExpression Id. */
  int MAXMAX = 33;
  /** RegularExpression Id. */
  int MAXMIN = 34;
  /** RegularExpression Id. */
  int MAX = 35;
  /** RegularExpression Id. */
  int MDP = 36;
  /** RegularExpression Id. */
  int MINMAX = 37;
  /** RegularExpression Id. */
  int MINMIN = 38;
  /** RegularExpression Id. */
  int MIN = 39;
  /** RegularExpression Id. */
  int MODULE = 40;
  /** RegularExpression Id. */
  int X = 41;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 42;
  /** RegularExpression Id. */
  int PMAXMAX = 43;
  /** RegularExpression Id. */
  int PMAXMIN = 44;
  /** RegularExpression Id. */
  int PMAX = 45;
  /** RegularExpression Id. */
  int PMINMAX = 46;
  /** RegularExpression Id. */
  int PMINMIN = 47;
  /** RegularExpression Id. */
  int PMIN = 48;
  /** RegularExpression Id. */
  int P = 49;
  /** RegularExpression Id. */
  int PLAYER = 50;
  /** RegularExpression Id. */
  int PROBABILISTIC = 51;
  /** RegularExpression Id. */
  int PROB = 52;
  /** RegularExpression Id. */
  int PTA = 53;
  /** RegularExpression Id. */
  int RATE = 54;
  /** RegularExpression Id. */
  int REWARDS = 55;
  /** RegularExpression Id. */
  int RMAXMAX = 56;
  /** RegularExpression Id. */
  int RMAXMIN = 57;
  /** RegularExpression Id. */
  int RMAX = 58;
  /** RegularExpression Id. */
  int RMINMAX = 59;
  /** RegularExpression Id. */
  int RMINMIN = 60;
  /** RegularExpression Id. */
  int RMIN = 61;
  /** RegularExpression Id. */
  int R = 62;
  /** RegularExpression Id. */
  int S = 63;
  /** RegularExpression Id. */
  int STOCHASTIC = 64;
  /** RegularExpression Id. */
  int STPG = 65;
  /** RegularExpression Id. */
  int SMG = 66;
  /** RegularExpression Id. */
  int SYSTEM = 67;
  /** RegularExpression Id. */
  int TRUE = 68;
  /** RegularExpression Id. */
  int U = 69;
  /** RegularExpression Id. */
  int W = 70;
  /** RegularExpression Id. */
  int NOT = 71;
  /** RegularExpression Id. */
  int AND = 72;
  /** RegularExpression Id. */
  int OR = 73;
  /** RegularExpression Id. */
  int IMPLIES = 74;
  /** RegularExpression Id. */
  int IFF = 75;
  /** RegularExpression Id. */
  int RARROW = 76;
  /** RegularExpression Id. */
  int COLON = 77;
  /** RegularExpression Id. */
  int SEMICOLON = 78;
  /** RegularExpression Id. */
  int COMMA = 79;
  /** RegularExpression Id. */
  int DOTS = 80;
  /** RegularExpression Id. */
  int LPARENTH = 81;
  /** RegularExpression Id. */
  int RPARENTH = 82;
  /** RegularExpression Id. */
  int LBRACKET = 83;
  /** RegularExpression Id. */
  int RBRACKET = 84;
  /** RegularExpression Id. */
  int LBRACE = 85;
  /** RegularExpression Id. */
  int RBRACE = 86;
  /** RegularExpression Id. */
  int EQ = 87;
  /** RegularExpression Id. */
  int NE = 88;
  /** RegularExpression Id. */
  int LT = 89;
  /** RegularExpression Id. */
  int GT = 90;
  /** RegularExpression Id. */
  int PATLL = 91;
  /** RegularExpression Id. */
  int PATLR = 92;
  /** RegularExpression Id. */
  int LE = 93;
  /** RegularExpression Id. */
  int GE = 94;
  /** RegularExpression Id. */
  int PLUS = 95;
  /** RegularExpression Id. */
  int MINUS = 96;
  /** RegularExpression Id. */
  int TIMES = 97;
  /** RegularExpression Id. */
  int DIVIDE = 98;
  /** RegularExpression Id. */
  int PRIME = 99;
  /** RegularExpression Id. */
  int RENAME = 100;
  /** RegularExpression Id. */
  int QMARK = 101;
  /** RegularExpression Id. */
  int DQUOTE = 102;
  /** RegularExpression Id. */
  int REG_INT = 103;
  /** RegularExpression Id. */
  int REG_DOUBLE = 104;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 105;
  /** RegularExpression Id. */
  int REG_IDENT = 106;
  /** RegularExpression Id. */
  int PREPROC = 107;
  /** RegularExpression Id. */
  int LEXICAL_ERROR = 108;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"A\"",
    "\"bool\"",
    "\"clock\"",
    "\"const\"",
    "\"ctmc\"",
    "\"ctmdp\"",
    "\"C\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"endinit\"",
    "\"endinvariant\"",
    "\"endmodule\"",
    "\"endplayer\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"func\"",
    "\"F\"",
    "\"Fc\"",
    "\"F0\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"invariant\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"maxmax\"",
    "\"maxmin\"",
    "\"max\"",
    "\"mdp\"",
    "\"minmax\"",
    "\"minmin\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmaxmax\"",
    "\"Pmaxmin\"",
    "\"Pmax\"",
    "\"Pminmax\"",
    "\"Pminmin\"",
    "\"Pmin\"",
    "\"P\"",
    "\"player\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmaxmax\"",
    "\"Rmaxmin\"",
    "\"Rmax\"",
    "\"Rminmax\"",
    "\"Rminmin\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"stpg\"",
    "\"smg\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"W\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<LEXICAL_ERROR>",
  };

}
