#!/bin/sh

# Startup script for PRISM preprocessor (beta)

# Launch using main PRISM script
PRISM_MAINCLASS="prism.Preprocessor"
export PRISM_MAINCLASS
/home/scratch/software/ModelCheckers/PRISM/development/prism/bin/prism "$@"
