#!/bin/bash

prism-games medium_access2.prism medium_access2.props -const emax=2,q1=0.9,q2=0.75 -prop 1 -const k=10
prism-games medium_access2.prism medium_access2.props -const emax=2,q1=0.9,q2=0.75 -prop 2
