#!/bin/bash

prism-games uav.prism uav.props -const accu_load1=0.9,accu_load2=0.8,fd=0.7,COUNTER=2,del=0.5 -prop 1

prism-games uav.prism uav.props -const accu_load1=0.9,accu_load2=0.8,fd=0.7,COUNTER=2,del=0.5 -prop 2 -logcpareto -multirounding -increasefactor 1.0 -baselineaccuracy 1000 -multimaxciter 100 -paretoepsilon 0.01 -pareto -gs
